name: GitHub Actions
on:
  workflow_dispatch:
    inputs:
      test-input:
        description: "Enter a string"
        default: "hello-world"
        required: true
        type: string
jobs:
  Use-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world!"
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - run: docker build -t cs-hunter-richards-file-metadata-image .
