name: generate interview.csv
on:
  workflow_dispatch:
    inputs:
      test-input:
        description: "Enter a label"
        default: "test run"
        required: true
        type: string
jobs:
  generate-csv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - run: docker build -t cs-hunter-richards-file-metadata-image .
      - run: docker run --name cs-hunter-richards-file-metadata --mount type=bind,source=$(pwd),target=/app/deliverable cs-hunter-richards-file-metadata-image:latest
      - run: cat interview.csv
